sudo: required
services:
    - docker

before_install:
    - docker build -t evgenii88/react-test -f ./client/Dockerfile.dev ./client

script:
    -  docker run -e CI=true evgenii88/react-test npm test


after_success:
    - docker build -t evgenii88/multi-client ./client
    - docker build -t evgenii88/multi-nginx ./nginx
    - docker build - t evgenii88/multi-server ./server
    - docker build -t evgenii88/multi-worker ./worker
    # log in to the docker cli
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

    # take images and push to dockerhub
    - docker push evgenii88/multi-client
    - docker push evgenii88/multi-nginx
    - docker push evgenii88/multi-server
    - docker push evgenii88/multi-worker
